### ISSUE TITLE
Testsuite errors on selected architectures with 1.7.1

### ISSUE THREAD

**Issue by ghisvail** [imageworks/Field3D#90]
Field3D used to build fine on all architectures with version 1.6.2. With version 1.7.1, the testsuite fails on selected architectures. Some of them are considered major and not fixing them would prevent the transition of the update to the next release.

Build logs for [1.6.2](https://buildd.debian.org/status/package.php?p=field3d) and [1.7.1](https://buildd.debian.org/status/package.php?p=field3d&suite=experimental). You can click on the `Build-Attempted` red labels to access the log.

Let me know if you need further information.

**Comment by magnusw** [comment]
I think this is a limitation with Ogawa, the new file format. It doesn't like big-endian systems. I will disable the Ogawa option on those systems.

std::runtime_error: Ogawa currently only supports little-endian writing.

**Comment by ghisvail** [comment]
Any news on that ?

**Comment by magnusw** [comment]
v1.7.2 should fix it. I've disabled the Ogawa back-end for big-endian
systems.

**Comment by ghisvail** [comment]
I have refreshed the packaging with `1.7.2` but the testsuite still fails fatally despite your fix. The build logs are available [here](https://buildd.debian.org/status/logs.php?pkg=field3d&ver=1.7.2-1~exp1&suite=experimental). Cheers.

**Comment by ghisvail** [comment]
Any news?

**Comment by r4f4** [comment]
To complement my comment above, the exception is

WARNING: In file: /tmp/test_SparseField_half_ogawa.f3d - Ogawa currently only supports little-endian reading.

That exception comes from OStream::init, right after an endianness check. So maybe the hdf5 fallback should also be tried in case of a std::runtime_error?

**Comment by magnusw** [comment]
Thank you for looking into this. Everything looks good in the PR, and it's
been merged into master. Ghislain - does this resolve the endian problem
for you?
